spring.application.name=database

#//mysql
##spring.datasource.url=jdbc:mysql://localhost:3306/play_dbr
##spring.datasource.username=root
##spring.datasource.password=12321
##spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
##spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#
//Post_sql
#spring.datasource.url=jdbc:postgresql://localhost:5432/SatyaDb
#spring.datasource.username=postgres
#spring.datasource.password=12321

//superbase
# spring.datasource.url=${SessionPooler}
spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres?user=postgres.usgpnwbhsxeavczwdurf&password=SatyaDeveloper@#0603
#spring.datasource.url=${DirectConnectcion}
#  spring.datasource.url=postgresql://postgres:[YOUR-PASSWORD]@db.usgpnwbhsxeavczwdurf.supabase.co:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================================
# HIKARI CONNECTION POOL
# =========================================

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000


# =========================================
# MYSQL
# =========================================
#mysql.datasource.url=jdbc:mysql://localhost:3306/play_dbr
#mysql.datasource.username=root
#mysql.datasource.password=12321
#mysql.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## =========================================
## POSTGRESQL
## =========================================
#
#postgres.datasource.url=jdbc:postgresql://localhost:5432/SatyaDb
#postgres.datasource.username=postgres
#postgres.datasource.password=12321
#postgres.datasource.driver-class-name=org.postgresql.Driver



//jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true






