#spring.application.name=database
#
#//post sql
#spring.database.url=""
#spring.database.username=""
#spring.database.password=""
#spring.database.driver-class-name=""
#
#//jpa
#spring.jpa.hibernate.ddl.auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.formate.sql=true
#spring.jpa.database-platform=
#
##spring.profiles.active= dev
#
